package openai

// Role is a role in the Chat Completion API. Conversations usually start with
// a system message first, then alternating user and assistant messages.
type Role string

// A SYSTEM message helps set the behavior of the assistant.
// It's the first message in a conversation.
const SYSTEM Role = "system"

// USER messages instruct the ASSISTANT. They can be generated by the end users
// of an application, or set by a developer as an instruction.
const USER Role = "user"

// ASSISTANT messages help store prior responses. They can also be written by a
// developer to help give examples of desired behavior.
const ASSISTANT Role = "assistant"

// Roles is a list of all valid Roles.
var Roles = []Role{SYSTEM, USER, ASSISTANT}

// String returns the string representation of a Role.
func (r Role) String() string {
	return string(r)
}

// IsValid returns true if the Role is valid.
func (r Role) IsValid() bool {
	for _, role := range Roles {
		if role == r {
			return true
		}
	}
	return false
}
